name: Build Agent

on:
  push:
    tags:
      - "v*"

jobs:
  build-agent-binaries:
    runs-on: ubuntu-latest
    env:
      OSQUERYI_CACHE_VERSION: 5.19.0
    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies for build scripts
        run: |
          sudo apt-get update
          sudo apt-get install -y zip coreutils wget

      - name: Set up Go
        run: |
          wget https://go.dev/dl/go1.25.5.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.25.5.linux-amd64.tar.gz
          echo "export PATH=$PATH:/usr/local/go/bin" >> ~/.bashrc
          source ~/.bashrc

      # - name: Setup python3
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.12

      # - name: Install python3-gdown for downloading the osqueryi binaries
      #   run: |
      #     pip3 install gdown

      # - name: Cache Osqueryi Binaries
      #   id: cache-osqueryi
      #   uses: actions/cache@v4
      #   with:
      #     path: agent/dist/builds-osqueryi
      #     key: osqueryi-${{ env.OSQUERYI_CACHE_VERSION }}

      # - name: Download Osqueryi Binaries
      #   if: steps.cache-osqueryi.outputs.cache-hit != 'true'
      #   run: |
      #     gdown --folder https://drive.google.com/drive/folders/1QcmbmLGlLxuWz-_fIqkBNyV2NKmH3G1R -O agent/dist/builds-osqueryi

      - name: Build Agent Binaries
        run: |
          cd agent && ./scripts/build.sh --yes

      - name: Extract version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "TAG=$GITHUB_REF_NAME" >> $GITHUB_ENV

      - name: Upload Agent build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scanx-${{ env.TAG }}
          path: agent/dist/${{ env.VERSION }}