name: Build Agent

on:
  push:
    tags:
      - "v*"

jobs:
  build-agent-binaries:
    runs-on: ubuntu-latest
    env:
      OSQUERYI_CACHE_VERSION: 5.19.0
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.5

      - name: Setup python3
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install system dependencies for build scripts
        run: |
          sudo apt-get update
          sudo apt-get install -y zip coreutils

      - name: Install python3-gdown for downloading the osqueryi binaries
        run: |
          pip3 install gdown

      - name: Cache Osqueryi Binaries
        id: cache-osqueryi
        uses: actions/cache@v4
        with:
          path: agent/dist/builds-osqueryi
          key: osqueryi-${{ env.OSQUERYI_CACHE_VERSION }}

      - name: Download Osqueryi Binaries
        if: steps.cache-osqueryi.outputs.cache-hit != 'true'
        run: |
          gdown --folder https://drive.google.com/drive/folders/1QcmbmLGlLxuWz-_fIqkBNyV2NKmH3G1R -O agent/dist/builds-osqueryi

      - name: Build Agent Binaries
        run: |
          cd agent && ./scripts/build.sh --yes && \
          ./scripts/create-linux-packages.sh 1 amd64 && \
          ./scripts/create-linux-packages.sh 1 arm64

      - name: Extract version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "TAG=$GITHUB_REF_NAME" >> $GITHUB_ENV

      - name: Upload Agent build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scanx-${{ env.TAG }}
          path: agent/dist/${{ env.VERSION }}